apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
namespace: prod
commonAnnotations:
  supported-by: sre@example.com
labels:
  - includeSelectors: false
    pairs:
      project: instavote
patches:
  - path: service.yaml
  - path: preview-service.yaml
  - path: rollout.yaml
